name: PR - Tests & SonarQube

inputs:
  SONAR_TOKEN:
    description: "SonarQube token"
    required: true
  UNIT_TESTS_COMMAND:
    description: "Run unit tests"
    required: true
  REPORT_PATH:
    description: "Path to the test report"
    required: true

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: ${{ UNIT_TESTS_COMMAND }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: ${{ inputs.REPORT_PATH }}

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: "60 80"

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        recreate: true
        path: code-coverage-results.md

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        args: >
          -Dsonar.python.coverage.reportPaths=coverage.xml
