name: PR - Tests & SonarQube

inputs:
  SONAR_TOKEN:
    description: 'SonarQube token'
    required: true

runs: 

  using: "composite"

  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        behave dev/tests/features --junit --junit-directory reports

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
